I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/go_outside.rpy", line 42, in script
    jump protagonist_home
ScriptError: could not find label 'protagonist_home'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/go_outside.rpy", line 42, in script
    jump protagonist_home
  File "C:\Users\Hikki\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Hikki\Documents\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'protagonist_home'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Dialogue Test 1.0
Fri Dec 29 15:20:30 2023
